version: "3"
services:
  db:
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      #MYSQL_DATABASE: evalart_reto
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
    - ./data:/docker-entrypoint-initdb.d